const theme = {
  // colors
  black: '#4F4F4F',
  white: '#FDFDFD',
  greyLight: '#F2F2F2',
  grey: '#E6E6E6',
  greyMedium: '#BFBFBF',
  greyDark: '#898989',
  green: '#00C7B1',
  greenDark: '#009681',
  blue: '#008EAA',
  blueDark: '#006272',
  yellow: '#FFDD00',
  yellowDark: '#F5AC00',
  successLight: '#D2F4D7',
  success: '#9AE0A5',
  successMedium: '#33A545',
  infoLight: '#D9EDF7',
  info: '#BFDFEF',
  infoMedium: '#3B9ECF',
  warningLight: '#FEF8D5',
  warning: '#F1E8B6',
  warningMedium: '#E0A74F',
  errorLight: '#FFE7E7',
  error: '#F5C4C4',
  errorMedium: '#FF585D',
  errorDark: '#C24242',
  // whitespace
  whitespaceXs: '6px',
  whitespaceS: '12px',
  whitespaceM: '24px',
  whitespaceL: '36px',
  whitespaceXl: '48px',
  whitespaceXxl: '72px',
  // fontSize
  fontSizeXxs: '8px',
  fontSizeXs: '12px',
  fontSizeS: '14px',
  fontSizeM: '16px',
  fontSizeL: '19px',
  fontSizeXl: '25px',
  fontSizeXxl: '35px',
  fontSizeXxxl: '45px',
  // borders
  borderRadius: '4px',
  borderWidth: '2px',
  // shadow
  boxShadow: '2px 2px 3px rgba(0,0,0,0.3)',
  fontHeading: '"Ubuntu", sans-serif',
  font: '"Open Sans", sans-serif',
  fontWeightBold: 700,
}

export default theme
